### ISSUE TITLE
CORs in filterProduct

### ISSUE THREAD

**Issue by andrianovartemii** [Company-Data-Graph/data-graph#11]
СORS при запросе выдает ошибку:
`
Access to XMLHttpRequest at 'http://<ip>:<port>/filterProduct' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
`

**Comment by MaksimTyanutov** [comment]
Fixed
