### ISSUE TITLE
Host and port is inline into code

### ISSUE THREAD

**Issue by andrianovartemii** [Company-Data-Graph/data-graph#8]
Хост и порт должны быть вынесены из кода и должны задаваться либо из файла конфигурации, либо в ключа/параметра при запуске программы

https://github.com/Company-Data-Graph/data-graph/blob/46187cfb88c97e46331ba28f9a4807f5a7c41b68/backend/pkg/apiServer/apiServer.go#L11

**Comment by MaksimTyanutov** [comment]
Добавил поля host и port в конфиг файл
